### PR TITLE
Type fix for application statements/execution_file

### PR DESCRIPTION
**Pull request by zhubonan**
This is a great package for building CLI tools!

But, I have received this error when building an application  (on Julia 1.6.1): 

```
┌ Info: application options: 
│   options.application =
│    ComoniconOptions.Application(;
│        filter_stdlibs = false,
│        precompile = ComoniconOptions.Precompile(;
│            execution_file = ["test/runtest.jl"],
│        ),
└    )
ERROR: LoadError: TypeError: in keyword argument precompile_statements_file, expected Union{String, Vector{String}}, got a value of type Vector{Union{Nothing, String}}
Stacktrace:
 [1] build_application(m::Module, options::ComoniconOptions.Comonicon)
   @ ComoniconBuilder ~/.julia/packages/ComoniconBuilder/I9tvS/src/build.jl:59
 [2] install(m::Module, options::ComoniconOptions.Comonicon)
   @ ComoniconBuilder ~/.julia/packages/ComoniconBuilder/I9tvS/src/install.jl:66
 [3] #install#1
```

I think the problem is that the following lines:

https://github.com/comonicon/ComoniconBuilder.jl/blob/22e532e4636d2ac520633cef03634a7b33dff3d9/src/build.jl#L56-L58

results an Array that can contain `nothing`. The `nothing` element should be filtered out instead. It works about replacing them with:

The change in this PR should make sure the type is `Vector{String}` instead of `Vector{Union{Nothing, String}}` in the same way it is for the system image function. 

One more thing, if any of the files listed is missing the error would be raised inside the array comprehension. 
Perhaps it is better to explicitly check for the existence of nothing and warn its implication (e.g. one of the files do not exist) to the user?

### CODE REVIEW

**Comment by Roger-luo** [comment]
thanks! good catch, I think it should instead return a `String[]` if no file is specified instead of adding type assertions? we don't have any type inference problem here

**Comment by zhubonan** [comment]
I see, then it is probably better to do array comprehension directly with `String[]` so the type is always `Vector{String}`.

**Comment by Roger-luo** [comment]
thanks! could you also put a test case for this?

**Comment by Roger-luo** [comment]
just realize github has this annoying CI approve thing, great job! let's just wait for CI to pass!

**Comment by zhubonan** [comment]
seems there is an issue while building the app against the latest nightly build (segfault...).  @Roger-luo Maybe the build test should be limited to the latest release for now?

**Comment by Roger-luo** [comment]
Yeah let's ignore the nightly for now

**Comment by Roger-luo** [comment]
LGTM thanks

**Comment by zhubonan** [comment]
No problem!
Seems that the CI still shows the failed state - I was not able to get my head around GitHub action 😂 I will leave that to you 😏 
Maybe worth making a bug fix release?

**Pull request merged**
